import {
  BarChart3,
  Bell,
  BookOpen,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  FileText,
  GraduationCap,
  LayoutDashboard,
  Megaphone,
  MessageSquare,
  NotebookTabs,
  Settings,
  ShieldCheck,
  Users,
} from "lucide-react";

type NavItem = {
  label: string;
  href: string;
  icon: typeof LayoutDashboard;
  color: string;
  bg: string;
  description?: string;
};

export const studentItems: NavItem[] = [
  {
    label: "Dashboard",
    href: "/student",
    icon: LayoutDashboard,
    color: "text-blue-600",
    bg: "bg-blue-50 dark:bg-blue-950/40",
    description: "Overview",
  },
  {
    label: "Profile",
    href: "/student/profile",
    icon: Users,
    color: "text-violet-600",
    bg: "bg-violet-50 dark:bg-violet-950/40",
    description: "My profile",
  },
  {
    label: "Attendance",
    href: "/student/attendance",
    icon: ClipboardCheck,
    color: "text-emerald-600",
    bg: "bg-emerald-50 dark:bg-emerald-950/40",
    description: "Attendance",
  },
  {
    label: "Timetable",
    href: "/student/timetable",
    icon: CalendarDays,
    color: "text-cyan-600",
    bg: "bg-cyan-50 dark:bg-cyan-950/40",
    description: "Schedule",
  },
  {
    label: "Subjects",
    href: "/student/subjects",
    icon: BookOpen,
    color: "text-indigo-600",
    bg: "bg-indigo-50 dark:bg-indigo-950/40",
    description: "Subjects",
  },
  {
    label: "Assignments",
    href: "/student/assignments",
    icon: NotebookTabs,
    color: "text-orange-600",
    bg: "bg-orange-50 dark:bg-orange-950/40",
    description: "Assignments",
  },
  {
    label: "Exams",
    href: "/student/exams",
    icon: GraduationCap,
    color: "text-pink-600",
    bg: "bg-pink-50 dark:bg-pink-950/40",
    description: "Examinations",
  },
  {
    label: "Results",
    href: "/student/results",
    icon: BarChart3,
    color: "text-purple-600",
    bg: "bg-purple-50 dark:bg-purple-950/40",
    description: "Results",
  },
  {
    label: "Fees",
    href: "/student/fees",
    icon: CreditCard,
    color: "text-amber-600",
    bg: "bg-amber-50 dark:bg-amber-950/40",
    description: "Payments",
  },
  {
    label: "Notices",
    href: "/student/notices",
    icon: Megaphone,
    color: "text-red-600",
    bg: "bg-red-50 dark:bg-red-950/40",
    description: "College notices",
  },
  {
    label: "Events",
    href: "/student/events",
    icon: CalendarDays,
    color: "text-teal-600",
    bg: "bg-teal-50 dark:bg-teal-950/40",
    description: "Events",
  },
  {
    label: "Materials",
    href: "/student/materials",
    icon: FileText,
    color: "text-sky-600",
    bg: "bg-sky-50 dark:bg-sky-950/40",
    description: "Study materials",
  },
  {
    label: "Leave",
    href: "/student/leave",
    icon: ClipboardList,
    color: "text-rose-600",
    bg: "bg-rose-50 dark:bg-rose-950/40",
    description: "Leave requests",
  },
  {
    label: "Certificates",
    href: "/student/certificates",
    icon: FileText,
    color: "text-yellow-600",
    bg: "bg-yellow-50 dark:bg-yellow-950/40",
    description: "Certificates",
  },
  {
    label: "Messages",
    href: "/student/messages",
    icon: MessageSquare,
    color: "text-green-600",
    bg: "bg-green-50 dark:bg-green-950/40",
    description: "Messages",
  },
  {
    label: "Notifications",
    href: "/student/notifications",
    icon: Bell,
    color: "text-fuchsia-600",
    bg: "bg-fuchsia-50 dark:bg-fuchsia-950/40",
    description: "Notifications",
  },
  {
    label: "Settings",
    href: "/student/settings",
    icon: Settings,
    color: "text-slate-600",
    bg: "bg-slate-100 dark:bg-slate-800",
    description: "Preferences",
  },
];

export const facultyItems: NavItem[] = [
  {
    label: "Dashboard",
    href: "/faculty",
    icon: LayoutDashboard,
    color: "text-blue-600",
    bg: "bg-blue-50 dark:bg-blue-950/40",
    description: "Overview",
  },
  {
    label: "Profile",
    href: "/faculty/profile",
    icon: Users,
    color: "text-violet-600",
    bg: "bg-violet-50 dark:bg-violet-950/40",
    description: "My profile",
  },
  {
    label: "Classes",
    href: "/faculty/classes",
    icon: GraduationCap,
    color: "text-indigo-600",
    bg: "bg-indigo-50 dark:bg-indigo-950/40",
    description: "My classes",
  },
  {
    label: "Students",
    href: "/faculty/students",
    icon: Users,
    color: "text-cyan-600",
    bg: "bg-cyan-50 dark:bg-cyan-950/40",
    description: "Students",
  },
  {
    label: "Attendance",
    href: "/faculty/attendance",
    icon: ClipboardCheck,
    color: "text-emerald-600",
    bg: "bg-emerald-50 dark:bg-emerald-950/40",
    description: "Attendance",
  },
  {
    label: "Assignments",
    href: "/faculty/assignments",
    icon: NotebookTabs,
    color: "text-orange-600",
    bg: "bg-orange-50 dark:bg-orange-950/40",
    description: "Assignments",
  },
  {
    label: "Marks",
    href: "/faculty/marks",
    icon: BarChart3,
    color: "text-purple-600",
    bg: "bg-purple-50 dark:bg-purple-950/40",
    description: "Marks",
  },
  {
    label: "Exams",
    href: "/faculty/exams",
    icon: GraduationCap,
    color: "text-pink-600",
    bg: "bg-pink-50 dark:bg-pink-950/40",
    description: "Examinations",
  },
  {
    label: "Materials",
    href: "/faculty/materials",
    icon: FileText,
    color: "text-sky-600",
    bg: "bg-sky-50 dark:bg-sky-950/40",
    description: "Materials",
  },
  {
    label: "Timetable",
    href: "/faculty/timetable",
    icon: CalendarDays,
    color: "text-teal-600",
    bg: "bg-teal-50 dark:bg-teal-950/40",
    description: "Schedule",
  },
  {
    label: "Leave",
    href: "/faculty/leave",
    icon: ClipboardList,
    color: "text-rose-600",
    bg: "bg-rose-50 dark:bg-rose-950/40",
    description: "Leave requests",
  },
  {
    label: "Notices",
    href: "/faculty/notices",
    icon: Megaphone,
    color: "text-red-600",
    bg: "bg-red-50 dark:bg-red-950/40",
    description: "Notices",
  },
  {
    label: "Messages",
    href: "/faculty/messages",
    icon: MessageSquare,
    color: "text-green-600",
    bg: "bg-green-50 dark:bg-green-950/40",
    description: "Messages",
  },
  {
    label: "Notifications",
    href: "/faculty/notifications",
    icon: Bell,
    color: "text-fuchsia-600",
    bg: "bg-fuchsia-50 dark:bg-fuchsia-950/40",
    description: "Notifications",
  },
  {
    label: "Settings",
    href: "/faculty/settings",
    icon: Settings,
    color: "text-slate-600",
    bg: "bg-slate-100 dark:bg-slate-800",
    description: "Preferences",
  },
];

export const adminItems: NavItem[] = [
  {
    label: "Dashboard",
    href: "/admin",
    icon: LayoutDashboard,
    color: "text-blue-600",
    bg: "bg-blue-50 dark:bg-blue-950/40",
    description: "Control center",
  },
  {
    label: "Users",
    href: "/admin/users",
    icon: Users,
    color: "text-violet-600",
    bg: "bg-violet-50 dark:bg-violet-950/40",
    description: "All users",
  },
  {
    label: "Students",
    href: "/admin/students",
    icon: Users,
    color: "text-cyan-600",
    bg: "bg-cyan-50 dark:bg-cyan-950/40",
    description: "Student records",
  },
  {
    label: "Faculty",
    href: "/admin/faculty",
    icon: GraduationCap,
    color: "text-indigo-600",
    bg: "bg-indigo-50 dark:bg-indigo-950/40",
    description: "Faculty records",
  },
  {
    label: "Subjects",
    href: "/admin/subjects",
    icon: NotebookTabs,
    color: "text-orange-600",
    bg: "bg-orange-50 dark:bg-orange-950/40",
    description: "Subjects",
  },
  {
    label: "Attendance",
    href: "/admin/attendance",
    icon: ClipboardCheck,
    color: "text-emerald-600",
    bg: "bg-emerald-50 dark:bg-emerald-950/40",
    description: "Attendance",
  },
  {
    label: "Timetable",
    href: "/admin/timetable",
    icon: CalendarDays,
    color: "text-teal-600",
    bg: "bg-teal-50 dark:bg-teal-950/40",
    description: "Schedules",
  },
  {
    label: "Exams",
    href: "/admin/exams",
    icon: GraduationCap,
    color: "text-pink-600",
    bg: "bg-pink-50 dark:bg-pink-950/40",
    description: "Examinations",
  },
  {
    label: "Results",
    href: "/admin/results",
    icon: BarChart3,
    color: "text-purple-600",
    bg: "bg-purple-50 dark:bg-purple-950/40",
    description: "Academic results",
  },
  {
    label: "Fees",
    href: "/admin/fees",
    icon: CreditCard,
    color: "text-amber-600",
    bg: "bg-amber-50 dark:bg-amber-950/40",
    description: "Fee management",
  },
  {
    label: "Notices",
    href: "/admin/notices",
    icon: Megaphone,
    color: "text-red-600",
    bg: "bg-red-50 dark:bg-red-950/40",
    description: "College notices",
  },
  {
    label: "Events",
    href: "/admin/events",
    icon: CalendarDays,
    color: "text-cyan-600",
    bg: "bg-cyan-50 dark:bg-cyan-950/40",
    description: "College events",
  },
  {
    label: "Queries",
    href: "/admin/queries",
    icon: MessageSquare,
    color: "text-green-600",
    bg: "bg-green-50 dark:bg-green-950/40",
    description: "Contact queries",
  },
  {
    label: "Reports",
    href: "/admin/reports",
    icon: BarChart3,
    color: "text-fuchsia-600",
    bg: "bg-fuchsia-50 dark:bg-fuchsia-950/40",
    description: "Analytics",
  },
  {
    label: "Messages",
    href: "/admin/messages",
    icon: MessageSquare,
    color: "text-sky-600",
    bg: "bg-sky-50 dark:bg-sky-950/40",
    description: "Inbox",
  },
  {
    label: "Notifications",
    href: "/admin/notifications",
    icon: Bell,
    color: "text-rose-600",
    bg: "bg-rose-50 dark:bg-rose-950/40",
    description: "Notifications",
  },
  {
    label: "Audit Logs",
    href: "/admin/audit-logs",
    icon: ShieldCheck,
    color: "text-slate-600",
    bg: "bg-slate-100 dark:bg-slate-800",
    description: "Security logs",
  },
  {
    label: "Settings",
    href: "/admin/settings",
    icon: Settings,
    color: "text-slate-600",
    bg: "bg-slate-100 dark:bg-slate-800",
    description: "System settings",
  },
];